### PR TITLE
[WIP]  add modulo operations to UInt

### PR DESCRIPTION
**Pull request by dignifiedquire**
version that fixes the proptests of #561

### CODE REVIEW

**Comment by dignifiedquire** [comment]
Note: `mul_mod` is definitely broken atm

**Comment by tarcieri** [comment]
I merged the rest except for `mul_mod` in #561

**Comment by tarcieri** [comment]
@dignifiedquire want to rebase or reopen with just `mul_mod`?

**Comment by tarcieri** [comment]
Most of this was implemented in #561.

Now that the repo is moved, `mul_mod` will need a new PR.

**Pull request closed without merging**
