### PR TITLE
Implement Divide and Modulo crypto-bigint

### PR DESCRIPTION
**Pull request by mikelodder7**
Implements Constant Time Divide and Remainder (Modulo) operations for BigInt

### CODE REVIEW

**Comment by mikelodder7** [comment]
Hmm might need some help with prop tests since num-bigint panics on zero but mine doesn’t

**Comment by tarcieri** [comment]
Looks good, thank you!

I have a few nits but also would really like to get `crypto-bigint` moved to a new home at:

https://github.com/rustcrypto/crypto-bigint

In the interest of getting this moved over I'm going to go ahead and merge this, and open some follow-ups there after the crate has been moved.

**Comment by mikelodder7** [comment]
Excellent. Feel free to let me know what to do to make it better

**Comment by tarcieri** [comment]
I was mostly concerned about nitpicking method names and things that maybe shouldn't be in the public API (yet)

**Comment by mikelodder7** [comment]
Right. Makes sense

**Pull request merged**
