### PR TITLE
zeroize v1.5.0

### PR DESCRIPTION
**Pull request by tarcieri**
### Added
- `Zeroize` impls for `PhantomData`, `PhantomPinned`, and tuples with 0-10 elements ([#660])
- `#[zeroize(bound = "T: MyTrait")]` ([#663])
- `ZeroizeOnDrop` trait and custom derive ([#699], [#700], [#703])

[#660]: https://github.com/RustCrypto/utils/pull/660
[#663]: https://github.com/RustCrypto/utils/pull/663
[#699]: https://github.com/RustCrypto/utils/pull/699
[#700]: https://github.com/RustCrypto/utils/pull/700
[#703]: https://github.com/RustCrypto/utils/pull/703

### CODE REVIEW

**Comment by dovahcrow** [comment]
Spent half an hour debugging derive macro `zeroize` not found issue when compiling a Solana program which depends on tiny-bip which depends on `zeroize` then found out it is because I was caught in between the release process of zeroize. What a sad story for the deep dependencies of open-source projects.

**Comment by tarcieri** [comment]
Please open an issue with a reproduction of your problem

**Comment by dovahcrow** [comment]
> Please open an issue with a reproduction of your problem

It's fixed after running cargo update. 

This crate is not working during the 30 mins period between the release of zeroize_derive 1.3.0 and zeroize 1.5.0. Unfortunately I did the cargo update right after zeroize_derive so everything breaks.

**Comment by tarcieri** [comment]
The new release of `zeroize_derive` should still be compatible with older versions of `zeroize`. If not, it's a bug.

**Comment by raphaelrobert** [comment]
I ran into a similar problem. Right now it looks like older versions (<=1.4.3) of zeroize don't work with rustc 1.58, but I need to investigate more.

**Comment by tarcieri** [comment]
If someone can post the exact error you're encountering that'd be very helpful

**Comment by daxpedda** [comment]
@tarcieri feel free to CC me when we find out what the issue is.

**Comment by raphaelrobert** [comment]
@daxpedda see #714.

**Comment by dovahcrow** [comment]
@raphaelrobert @daxpedda @tarcieri added the repro to #714

**Pull request merged**
