### PR TITLE
add shl

### PR DESCRIPTION
**Pull request by mikelodder7**
Signed-off-by: Michael Lodder <redmike7@gmail.com>

### CODE REVIEW

**Comment by tarcieri** [comment]
Hmm, tests appear to be failing?

**Comment by mikelodder7** [comment]
Yeah hmm. Investigating

**Comment by mikelodder7** [comment]
Passing

**Review by tarcieri — APPROVED** [review]
@mikelodder7 looks good!

Optionally you could consider adding some proptests against a `num-bigint` reference under `proptests/tests`, although FWIW we don't presently have any for `shr`

**Comment by mikelodder7** [comment]
I can add those if you'd prefer. But I'd like to do that in a subsequent PR

**Comment by tarcieri** [comment]
Sounds good!

**Pull request merged**
